-- Deprecated legacy SQLite schema retained as historical source material.
-- The application never executes this destructive script. Use:
--   python -m boiler_reviews.db.migrate upgrade
-- for ordered, non-destructive migrations. Use boiler_reviews.db.legacy for
-- validating/importing the old four-table database.
